// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz50UCuZBVR6H1jLRJucpTBempuvP_RgU',
    appId: '1:635601252419:web:f9aade3e22540b74b1e4f6',
    messagingSenderId: '635601252419',
    projectId: 'erp-pos-e1242',
    authDomain: 'erp-pos-e1242.firebaseapp.com',
    storageBucket: 'erp-pos-e1242.firebasestorage.app',
    measurementId: 'G-XJS8881WNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2ZIAhRrs1HbNTMdf-BeKV4YXyNHXpNs',
    appId: '1:635601252419:android:b5d4945864a4755cb1e4f6',
    messagingSenderId: '635601252419',
    projectId: 'erp-pos-e1242',
    storageBucket: 'erp-pos-e1242.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvv2P-WMt3H6z7OvF8ecO3xPGARifTvgM',
    appId: '1:635601252419:ios:28469ec9f749f360b1e4f6',
    messagingSenderId: '635601252419',
    projectId: 'erp-pos-e1242',
    storageBucket: 'erp-pos-e1242.firebasestorage.app',
    iosBundleId: 'com.example.bluetoothPrinter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvv2P-WMt3H6z7OvF8ecO3xPGARifTvgM',
    appId: '1:635601252419:ios:28469ec9f749f360b1e4f6',
    messagingSenderId: '635601252419',
    projectId: 'erp-pos-e1242',
    storageBucket: 'erp-pos-e1242.firebasestorage.app',
    iosBundleId: 'com.example.bluetoothPrinter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz50UCuZBVR6H1jLRJucpTBempuvP_RgU',
    appId: '1:635601252419:web:7d45867f5c0bcb64b1e4f6',
    messagingSenderId: '635601252419',
    projectId: 'erp-pos-e1242',
    authDomain: 'erp-pos-e1242.firebaseapp.com',
    storageBucket: 'erp-pos-e1242.firebasestorage.app',
    measurementId: 'G-8BJ84FDKHW',
  );
}
